import { Router, type IRouter } from "express";
import healthRouter from "./health";
import publicRouter from "./public";
import authRouter from "./auth";
import outletsRouter from "./outlets";
import staffRouter from "./staff";
import menuRouter from "./menu";
import modifiersRouter from "./modifiers";
import areasRouter from "./areas";
import tablesRouter from "./tables";
import ordersRouter from "./orders";
import kitchenRouter from "./kitchen";
import reportsRouter from "./reports";
import customersRouter from "./customers";
import storageRouter from "./storage";
import inventoryRouter from "./inventory";
import eventsRouter from "./events";
import settingsRouter from "./settings";
import purchasesRouter from "./purchases";

const router: IRouter = Router();

router.use(eventsRouter);
router.use(healthRouter);
router.use(publicRouter);
router.use(authRouter);
router.use(outletsRouter);
router.use(staffRouter);
router.use(menuRouter);
router.use(modifiersRouter);
router.use(areasRouter);
router.use(tablesRouter);
router.use(ordersRouter);
router.use(kitchenRouter);
router.use(reportsRouter);
router.use(customersRouter);
router.use(storageRouter);
router.use(inventoryRouter);
router.use(purchasesRouter);
router.use(settingsRouter);

export default router;
