#!/usr/bin/env bash
# Pull Railway MioPoS + Postgres variables into .env.local (matches production config).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if ! command -v railway >/dev/null 2>&1; then
  echo "Railway CLI not found. Install: bash <(curl -fsSL https://railway.com/install.sh)" >&2
  exit 1
fi

# shellcheck disable=SC1091
[[ -f "$HOME/.railway/env" ]] && source "$HOME/.railway/env"

railway_var() {
  railway run --service MioPoS printenv "$1" 2>/dev/null | tail -1 | tr -d '\r' || true
}

echo "==> Fetching variables from Railway (Postgres + MioPoS services)..."
DATABASE_URL="$(railway run --service Postgres printenv DATABASE_PUBLIC_URL 2>/dev/null | tail -1 | tr -d '\r')"
SESSION_SECRET="$(railway_var SESSION_SECRET)"

PUBLIC_OBJECT_SEARCH_PATHS="$(railway_var PUBLIC_OBJECT_SEARCH_PATHS)"
PRIVATE_OBJECT_DIR="$(railway_var PRIVATE_OBJECT_DIR)"
GCS_SERVICE_ACCOUNT_JSON="$(railway_var GCS_SERVICE_ACCOUNT_JSON)"

if [[ -z "$DATABASE_URL" ]]; then
  echo "Could not read DATABASE_PUBLIC_URL. Run: railway link  (project mio-pos)" >&2
  exit 1
fi

if [[ -z "$SESSION_SECRET" ]]; then
  SESSION_SECRET="local-dev-$(openssl rand -hex 16 2>/dev/null || echo change-me)"
  echo "    (no SESSION_SECRET on MioPoS — generated a local one)"
fi

{
  echo "# Generated by scripts/pull-env-from-railway.sh on $(date -u +"%Y-%m-%dT%H:%MZ")"
  echo "DATABASE_URL=$DATABASE_URL"
  echo "SESSION_SECRET=$SESSION_SECRET"
  echo "NODE_ENV=development"
  echo "BASE_PATH=/"
  echo "API_PORT=8787"
  echo "VITE_PORT=5173"
  if [[ -n "$PUBLIC_OBJECT_SEARCH_PATHS" ]]; then
    echo "PUBLIC_OBJECT_SEARCH_PATHS=$PUBLIC_OBJECT_SEARCH_PATHS"
  fi
  if [[ -n "$PRIVATE_OBJECT_DIR" ]]; then
    echo "PRIVATE_OBJECT_DIR=$PRIVATE_OBJECT_DIR"
  fi
  if [[ -n "$GCS_SERVICE_ACCOUNT_JSON" ]]; then
    echo "GCS_SERVICE_ACCOUNT_JSON=$GCS_SERVICE_ACCOUNT_JSON"
  fi
} > .env.local

echo "==> Wrote .env.local"
echo "    Do not commit this file (contains secrets)."
if [[ -z "$PUBLIC_OBJECT_SEARCH_PATHS" || -z "$PRIVATE_OBJECT_DIR" ]]; then
  echo "    Tip: Set PUBLIC_OBJECT_SEARCH_PATHS and PRIVATE_OBJECT_DIR on Railway for slip uploads in production."
fi
